"use client";

import { useEffect, useState } from "react";
import { Sparkle20Regular } from "@fluentui/react-icons";
import { SectionCard } from "@/components/ui/KpiGrid";
import { Badge } from "@/components/ui/Badge";
import { Spinner } from "@/components/ui/Spinner";
import type { AiInsightRecord, FindingSeverity } from "@/lib/aiInsights";

const SEVERITY_TIER: Record<FindingSeverity, "good" | "warn" | "bad"> = {
  info: "good",
  warning: "warn",
  critical: "bad",
};

/** Displays the latest daily AI digest (generated by scripts/ai-insights-sync.ps1
 *  → /api/ai-insights/generate, once per day) — this card only ever reads the
 *  most recent stored AiInsight, it never calls Claude itself. */
export function AiInsightsCard() {
  const [status, setStatus] = useState<"loading" | "idle" | "error">("loading");
  const [insight, setInsight] = useState<AiInsightRecord | null>(null);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch("/api/ai-insights", { cache: "no-store" });
        const body = await res.json();
        if (!res.ok) throw new Error(body.error || "Failed to load AI insights.");
        if (!cancelled) {
          setInsight(body.insight);
          setStatus("idle");
        }
      } catch {
        if (!cancelled) setStatus("error");
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  if (status === "loading") {
    return (
      <SectionCard title="AI Insights">
        <div className="flex items-center justify-center py-6">
          <Spinner className="h-5 w-5" />
        </div>
      </SectionCard>
    );
  }

  if (status === "error" || !insight) {
    return (
      <SectionCard title="AI Insights" action={<Sparkle20Regular className="h-4 w-4 text-muted" />}>
        <p className="px-1 py-2 text-xs text-muted">
          {status === "error" ? "Couldn't load AI insights." : "No digest generated yet — the daily job runs automatically."}
        </p>
      </SectionCard>
    );
  }

  return (
    <SectionCard
      title="AI Insights"
      action={<span className="text-xs text-muted">{new Date(insight.generatedAt).toLocaleString()}</span>}
    >
      <p className="px-1 text-sm text-foreground leading-relaxed">{insight.summary}</p>
      {insight.findings.length > 0 ? (
        <div className="mt-3 flex flex-col gap-2 px-1">
          {insight.findings.map((f, i) => (
            <div key={i} className="flex items-start gap-2">
              <Badge tier={SEVERITY_TIER[f.severity]}>{f.severity}</Badge>
              <div className="min-w-0">
                <div className="text-xs font-semibold text-foreground">{f.title}</div>
                <div className="text-xs text-muted">{f.detail}</div>
              </div>
            </div>
          ))}
        </div>
      ) : null}
    </SectionCard>
  );
}
