"use client";

import { useEffect, useState, type ReactNode } from "react";
import Link from "next/link";
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowLeft20Regular, BuildingShop20Regular, Dismiss12Regular, PeopleTeam20Regular, Timer20Regular } from "@fluentui/react-icons";
import { SectionCard } from "@/components/ui/KpiGrid";
import { TableWrap, Td, Th, Thead } from "@/components/ui/Table";
import { FullPageSpinner } from "@/components/ui/Spinner";
import { EmptyState } from "@/components/ui/EmptyState";
import { CHART_AXIS_COLOR, CHART_COLORS, CHART_GRID_COLOR, tooltipContentStyle, tooltipLabelStyle } from "@/components/charts/theme";
import { recentMonthOptions } from "@/lib/timeManagement";

interface Summary {
  scope: string; month: string; syncUpdatedAt: string | null;
  metrics: { calls: number; productiveCalls: number; customers: number; reps: number; netSales: number; averageDuration: number | null };
  daily: Array<{ date: string; calls: number; productiveCalls: number; netSales: number }>;
  hourly: Array<{ hour: number; calls: number; netSales: number }>;
  segments: Array<{ segment: string; calls: number; productiveCalls: number; netSales: number }>;
  reps: Array<{ salesman: string; agent: string | null; calls: number; productiveCalls: number; customers: number; netSales: number; averageDuration: number | null }>;
  filters: { reps: string[]; segments: string[] };
}
interface RepDetail { salesman: string; visits: Array<{ callDate: string; customerName: string; customerType: string | null; segment: string | null; timeIn: string | null; timeOut: string | null; durationMinutes: number | null; netSales: number; isProductive: boolean; callsInDay: number; productiveCallsInDay: number; dayStrikeRatePct: number | null }> }

const number = (value: number) => value.toLocaleString("en-KE", { maximumFractionDigits: 0 });
const currency = (value: number) => value.toLocaleString("en-KE", { style: "currency", currency: "KES", notation: "compact", maximumFractionDigits: 1 });
const pct = (yes: number, all: number) => all ? `${((yes / all) * 100).toFixed(1)}%` : "—";
const date = (value: string) => new Intl.DateTimeFormat("en-KE", { day: "numeric", month: "short" }).format(new Date(value));
const time = (value: string | null) => value ? new Intl.DateTimeFormat("en-KE", { hour: "numeric", minute: "2-digit", hour12: true }).format(new Date(value)) : "—";

function Metric({ label, value, icon }: { label: string; value: string; icon?: ReactNode }) {
  return <div className="rounded-xl border border-border bg-surface p-3"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-muted">{icon}{label}</div><p className="mt-2 text-xl font-bold tabular-nums text-brand-navy">{value}</p></div>;
}

function RepDrawer({ detail, close }: { detail: RepDetail | null; close: () => void }) {
  if (!detail) return null;
  return <div className="fixed inset-0 z-50 flex justify-end bg-brand-navy/35 p-0 sm:p-4" role="dialog" aria-modal="true" aria-label="EABL sales rep calls">
    <button className="absolute inset-0 cursor-default" aria-label="Close EABL rep detail" onClick={close} />
    <aside className="relative flex h-full w-full max-w-5xl flex-col overflow-hidden bg-background shadow-2xl sm:rounded-2xl">
      <header className="flex items-center justify-between border-b border-border bg-surface px-5 py-4"><div><p className="text-[10px] font-semibold uppercase tracking-wide text-primary-blue">EABL Call Performance</p><h2 className="mt-1 text-xl font-bold text-brand-navy">{detail.salesman}</h2><p className="mt-1 text-xs text-muted">Chronological customer call detail</p></div><button type="button" onClick={close} className="rounded-full border border-border p-2 text-muted hover:bg-surface-active" aria-label="Close"><Dismiss12Regular /></button></header>
      <div className="flex-1 overflow-auto p-4 sm:p-5"><SectionCard title="Customer call timeline" action={<span className="text-xs text-muted">Earliest → latest</span>}><TableWrap><Thead><Th>Date</Th><Th>Time</Th><Th>Customer</Th><Th>Segment</Th><Th align="right">Duration</Th><Th>Outcome</Th><Th align="right">Net sales</Th><Th align="right">Daily calls</Th><Th align="right">Day strike</Th></Thead><tbody>{detail.visits.map((visit, index) => <tr key={`${visit.callDate}-${visit.customerName}-${index}`}><Td>{date(visit.callDate)}</Td><Td>{time(visit.timeIn)}</Td><Td><span className="font-semibold text-brand-navy">{visit.customerName}</span><span className="block text-[11px] text-muted">{visit.customerType ?? "—"}</span></Td><Td>{visit.segment ?? "Unassigned"}</Td><Td align="right">{visit.durationMinutes === null ? "—" : `${visit.durationMinutes}m`}</Td><Td><span className={visit.isProductive ? "font-semibold text-emerald-700" : "text-muted"}>{visit.isProductive ? "Productive" : "No sale"}</span></Td><Td align="right">{currency(visit.netSales)}</Td><Td align="right">{visit.productiveCallsInDay}/{visit.callsInDay}</Td><Td align="right">{visit.dayStrikeRatePct === null ? "—" : `${visit.dayStrikeRatePct.toFixed(1)}%`}</Td></tr>)}</tbody></TableWrap></SectionCard></div>
    </aside>
  </div>;
}

export default function EablCallPerformancePage() {
  const [month, setMonth] = useState(() => recentMonthOptions(new Date(), 6)[0]);
  const [rep, setRep] = useState(""); const [segment, setSegment] = useState("");
  const [summary, setSummary] = useState<Summary | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const [detail, setDetail] = useState<RepDetail | null>(null);
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(false); const params = new URLSearchParams({ month }); if (rep) params.set("rep", rep); if (segment) params.set("segment", segment); fetch(`/api/eabl-call-performance/summary?${params}`, { cache: "no-store", signal: controller.signal }).then(async (response) => { if (!response.ok) throw new Error(); return response.json() as Promise<Summary>; }).then(setSummary).catch((err) => { if (err.name !== "AbortError") setError(true); }).finally(() => setLoading(false)); return () => controller.abort(); }, [month, rep, segment]);
  const openRep = (salesman: string) => fetch(`/api/eabl-call-performance/rep-detail?${new URLSearchParams({ rep: salesman, month })}`, { cache: "no-store" }).then((res) => res.ok ? res.json() as Promise<RepDetail> : Promise.reject()).then(setDetail);
  if (loading && !summary) return <FullPageSpinner label="Loading EABL Call Performance..." />;
  if (error || !summary) return <EmptyState icon={<Timer20Regular className="h-10 w-10" />} title="EABL Call Performance is not available yet" description="The module is ready, but its isolated SQL Server feed must be configured and synced before data can be shown." />;
  const metrics = summary.metrics;
  return <main className="mx-auto flex max-w-[1600px] flex-col gap-5 px-4 py-5 sm:px-6 lg:px-8">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><Link href="/timestamps" className="inline-flex items-center gap-1 text-xs font-semibold text-primary-blue hover:underline"><ArrowLeft20Regular className="h-4 w-4" /> Timestamps</Link><h1 className="mt-2 text-2xl font-bold text-brand-navy">EABL – Call Performance</h1><p className="mt-1 text-sm text-muted">Dedicated call-level activity for {summary.scope}; separate from the standard Pine timestamp feed.</p></div><span className="rounded-full bg-accent-blue-soft px-3 py-1 text-xs font-semibold text-primary-blue">{summary.syncUpdatedAt ? `Synced ${new Date(summary.syncUpdatedAt).toLocaleString("en-KE")}` : "Awaiting first sync"}</span></div>
    <div className="grid gap-3 rounded-xl border border-border bg-background-elevated/35 p-3 md:grid-cols-3"><label className="text-xs font-semibold text-muted">Month<select value={month} onChange={(e) => setMonth(e.target.value)} className="mt-1 block w-full rounded-lg border border-border bg-surface px-3 py-2 text-sm text-brand-navy">{recentMonthOptions(new Date(), 6).map((m) => <option key={m}>{m}</option>)}</select></label><label className="text-xs font-semibold text-muted">Salesman<select value={rep} onChange={(e) => setRep(e.target.value)} className="mt-1 block w-full rounded-lg border border-border bg-surface px-3 py-2 text-sm text-brand-navy"><option value="">All salesmen</option>{summary.filters.reps.map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-xs font-semibold text-muted">Customer segment<select value={segment} onChange={(e) => setSegment(e.target.value)} className="mt-1 block w-full rounded-lg border border-border bg-surface px-3 py-2 text-sm text-brand-navy"><option value="">All segments</option>{summary.filters.segments.map((value) => <option key={value}>{value}</option>)}</select></label></div>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-7"><Metric label="Calls" value={number(metrics.calls)} icon={<Timer20Regular />} /><Metric label="Productive" value={number(metrics.productiveCalls)} /><Metric label="Strike rate" value={pct(metrics.productiveCalls, metrics.calls)} /><Metric label="Net sales" value={currency(metrics.netSales)} /><Metric label="Customers" value={number(metrics.customers)} icon={<BuildingShop20Regular />} /><Metric label="Salesmen" value={number(metrics.reps)} icon={<PeopleTeam20Regular />} /><Metric label="Avg call" value={metrics.averageDuration === null ? "—" : `${metrics.averageDuration.toFixed(0)}m`} /></div>
    <div className="grid gap-5 xl:grid-cols-2"><SectionCard title="Daily call performance" action={<span className="text-xs text-muted">Calls and productive calls</span>}><ResponsiveContainer width="100%" height={260}><LineChart data={summary.daily.map((r) => ({ ...r, label: date(r.date) }))}><CartesianGrid stroke={CHART_GRID_COLOR} strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" stroke={CHART_AXIS_COLOR} fontSize={10} /><YAxis stroke={CHART_AXIS_COLOR} fontSize={10} /><Tooltip contentStyle={tooltipContentStyle} labelStyle={tooltipLabelStyle} /><Legend /><Line type="monotone" dataKey="calls" name="Calls" stroke={CHART_COLORS[0]} strokeWidth={2} dot={false} /><Line type="monotone" dataKey="productiveCalls" name="Productive" stroke={CHART_COLORS[1]} strokeWidth={2} dot={false} /></LineChart></ResponsiveContainer></SectionCard><SectionCard title="Call start-time pattern" action={<span className="text-xs text-muted">Calls by hour of check-in</span>}><ResponsiveContainer width="100%" height={260}><BarChart data={summary.hourly.map((r) => ({ ...r, label: `${r.hour}:00` }))}><CartesianGrid stroke={CHART_GRID_COLOR} strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" stroke={CHART_AXIS_COLOR} fontSize={10} /><YAxis stroke={CHART_AXIS_COLOR} fontSize={10} /><Tooltip contentStyle={tooltipContentStyle} labelStyle={tooltipLabelStyle} /><Bar dataKey="calls" name="Calls" fill={CHART_COLORS[0]} radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></SectionCard></div>
    <div className="grid gap-5 xl:grid-cols-2"><SectionCard title="Segment strike rate"><TableWrap><Thead><Th>Segment</Th><Th align="right">Calls</Th><Th align="right">Productive</Th><Th align="right">Strike rate</Th><Th align="right">Net sales</Th></Thead><tbody>{summary.segments.map((row) => <tr key={row.segment}><Td>{row.segment}</Td><Td align="right">{number(row.calls)}</Td><Td align="right">{number(row.productiveCalls)}</Td><Td align="right">{pct(row.productiveCalls, row.calls)}</Td><Td align="right">{currency(row.netSales)}</Td></tr>)}</tbody></TableWrap></SectionCard><SectionCard title="Salesman leaderboard" action={<span className="text-xs text-muted">Click a name for customer calls</span>}><TableWrap><Thead><Th>Salesman</Th><Th align="right">Calls</Th><Th align="right">Customers</Th><Th align="right">Strike rate</Th><Th align="right">Net sales</Th></Thead><tbody>{summary.reps.map((row) => <tr key={row.salesman}><Td><button type="button" onClick={() => openRep(row.salesman)} className="font-semibold text-primary-blue hover:underline">{row.salesman}</button>{row.agent ? <span className="block text-[11px] text-muted">{row.agent}</span> : null}</Td><Td align="right">{number(row.calls)}</Td><Td align="right">{number(row.customers)}</Td><Td align="right">{pct(row.productiveCalls, row.calls)}</Td><Td align="right">{currency(row.netSales)}</Td></tr>)}</tbody></TableWrap></SectionCard></div>
    <RepDrawer detail={detail} close={() => setDetail(null)} />
  </main>;
}
