// True month-to-date Target per Team Leader, for TL/Supervisor/Manager Ranking.
//
// buildTlRanking's mtdTarget has been wrong through two prior attempts:
//
// 1. Originally a straight sum of every WeeklyTarget row for the month (all
//    weeks, including ones that haven't started) - a full-month figure
//    mislabeled "MTD," and fragmented by legacy Team Leader identities
//    (orphaned pre-restructuring WeeklyTarget history under a stale
//    teamLeaderId nobody currently reports through).
// 2. Then switched to summing DailyTarget (which weekday-expands each
//    WeeklyTarget row) capped at today - fixed the elapsed-days problem, but
//    DailyTarget is generated by exploding WeeklyTarget rows against whichever
//    reps are CURRENTLY active under that row's exact teamLeaderId+principal
//    pair (recomputeDailyTargets, lib/repContribution.ts). A Supervisor whose
//    real reps sit under newer Team Leader identities, while their own legacy
//    teamLeaderId carries the real WeeklyTarget money but zero active reps,
//    still collapsed to a near-zero MTD Target (confirmed live: Lucy Githinji
//    ~5K against a ~90M monthly target).
//
// This version instead cascades the admin-entered Target.valueTarget (the same
// number already shown correctly on Sales Performance vs Target) down through
// RepContribution.sharePct (which sums to 100% among a principal's currently
// active Primary reps) to Team Leader, then prorates by elapsed working days.
// Driven entirely by current rosters/contributions - a Team Leader with zero
// currently-active Primary reps simply never enters the output, so no
// legacy-identity special-casing is needed on the target side at all.
import { prisma } from "@/lib/db";
import { CANONICAL_MONTHS } from "@/lib/timeIntelligence";
import { resolveRepSharePct } from "@/lib/repContribution";

export interface MtdTargetRow {
  teamLeaderId: string;
  targetValue: number;
  /** The same cascade's full-month figure, before the working-days proration -
   *  every Team Leader's monthlyTargetValue sums up to exactly the principal
   *  Target totals it was split from (contribution shares sum to 100%), so
   *  Supervisor/Manager rollups of this tie out to the overall month target. */
  monthlyTargetValue: number;
}

/** Mon-Fri, matching the work-week definition lib/repContribution.ts already
 *  uses to weekday-expand WeeklyTarget into DailyTarget (WEEKDAY_LABELS) -
 *  reused here rather than inventing a second definition. */
function isWorkingDay(date: Date): boolean {
  const day = date.getUTCDay();
  return day >= 1 && day <= 5;
}

/** Every Mon-Fri UTC calendar day in the given month. */
export function countWorkingDaysInMonth(year: number, monthIndex: number): number {
  const daysInMonth = new Date(Date.UTC(year, monthIndex + 1, 0)).getUTCDate();
  let count = 0;
  for (let d = 1; d <= daysInMonth; d++) {
    if (isWorkingDay(new Date(Date.UTC(year, monthIndex, d)))) count++;
  }
  return count;
}

/** Working days from the 1st through `today` inclusive - 0 if `today` is
 *  before the month starts, every working day in the month if `today` is
 *  after it ends (a fully-elapsed past month counts as 100% done). */
export function countElapsedWorkingDays(year: number, monthIndex: number, today: Date = new Date()): number {
  const monthStart = new Date(Date.UTC(year, monthIndex, 1));
  const daysInMonth = new Date(Date.UTC(year, monthIndex + 1, 0)).getUTCDate();
  const monthEnd = new Date(Date.UTC(year, monthIndex, daysInMonth));
  const todayUtc = new Date(Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate()));

  if (todayUtc < monthStart) return 0;
  const through = todayUtc > monthEnd ? monthEnd : todayUtc;

  let count = 0;
  for (let d = new Date(monthStart); d <= through; d = new Date(d.getTime() + 86400000)) {
    if (isWorkingDay(d)) count++;
  }
  return count;
}

export interface MtdTargetInputs {
  /** One row per principal, e.g. from Target.findMany - the admin-entered
   *  monthly figure, already shown correctly on Sales Performance vs Target. */
  principalTargets: { principal: string; valueTarget: number | null }[];
  /** Active, PRIMARY-role TeamLeaderAssignment rows only - actual SAP sales
   *  targets are a Primary concern (see lib/repContribution.ts's header note). */
  assignments: { teamLeaderId: string; principal: string; employeeCode: string; contributionPct: number | null }[];
  /** RepContribution rows - a rep's share of a principal's trailing revenue
   *  among reps currently assigned to it. */
  contributions: { principal: string; employeeCode: string; sharePct: number }[];
}

/** Splits each principal's monthly Target across its currently-active Primary
 *  reps by contribution share, rolls that up to Team Leader, then prorates by
 *  elapsed working days.
 *
 *  Groups by PRINCIPAL first (not teamLeaderId+principal) and re-normalizes
 *  every rep's resolved share so the group always sums to exactly 1.0 before
 *  applying it to the principal Target - confirmed live: TeamLeaderAssignment
 *  .contributionPct is "validated in the admin UI, not enforced at the DB
 *  level" (see its own schema comment), and one Supervisor's declared %'s
 *  across her 5 Team Leaders summed to 285%, not 100% (Lucy Githinji/Mars-
 *  Nairobi: 92.7M principal target rolled up to a 264M Supervisor total).
 *  Grouping by teamLeaderId+principal and trusting each rep's raw resolved
 *  share independently - the previous approach - had no defense against that:
 *  a badly-declared or duplicated (matrix-assigned) rep's share simply added
 *  up to whatever it added up to, with nothing forcing the total back to the
 *  principal's own number. Normalizing per principal is what actually
 *  guarantees a Supervisor/Manager rollup ties out exactly to the overall
 *  month target, which is the entire point of sourcing this cascade from
 *  Target instead of WeeklyTarget in the first place - the rep-level split is
 *  a means to attribute that total to a Team Leader, not a second source of
 *  truth for the total itself. A rep active under more than one Team Leader
 *  for the same principal (matrix org) appears once per assignment row here;
 *  normalization still keeps the group's total at exactly 100% of the
 *  principal target, it just gives that rep's combined total double relative
 *  weight against reps who are only assigned once - no separate handling
 *  needed. */
export function computeMtdTargetByTeamLeader(inputs: MtdTargetInputs, workingDaysElapsed: number, workingDaysInMonth: number): MtdTargetRow[] {
  const { principalTargets, assignments, contributions } = inputs;

  const targetByPrincipal = new Map(principalTargets.map((t) => [t.principal, t.valueTarget ?? 0]));
  const shareByPrincipalRep = new Map(contributions.map((c) => [`${c.principal}|${c.employeeCode}`, c.sharePct]));

  const repsByPrincipal = new Map<string, { teamLeaderId: string; employeeCode: string; contributionPct: number | null }[]>();
  for (const a of assignments) {
    const list = repsByPrincipal.get(a.principal) ?? [];
    list.push({ teamLeaderId: a.teamLeaderId, employeeCode: a.employeeCode, contributionPct: a.contributionPct });
    repsByPrincipal.set(a.principal, list);
  }

  const prorateFactor = workingDaysInMonth > 0 ? workingDaysElapsed / workingDaysInMonth : 0;
  const monthlyTargetByTeamLeader = new Map<string, number>();

  for (const [principal, reps] of repsByPrincipal) {
    const principalTarget = targetByPrincipal.get(principal) ?? 0;
    if (principalTarget === 0) continue;

    const rawShares = reps.map((rep) => resolveRepSharePct(rep.contributionPct, shareByPrincipalRep.get(`${principal}|${rep.employeeCode}`), 1 / reps.length));
    const rawSum = rawShares.reduce((s, v) => s + v, 0);

    reps.forEach((rep, i) => {
      const normalizedShare = rawSum > 0 ? rawShares[i] / rawSum : 1 / reps.length;
      const sum = monthlyTargetByTeamLeader.get(rep.teamLeaderId) ?? 0;
      monthlyTargetByTeamLeader.set(rep.teamLeaderId, sum + principalTarget * normalizedShare);
    });
  }

  return Array.from(monthlyTargetByTeamLeader.entries()).map(([teamLeaderId, monthlyTarget]) => ({
    teamLeaderId,
    targetValue: monthlyTarget * prorateFactor,
    monthlyTargetValue: monthlyTarget,
  }));
}

/** Async wrapper: fetches this month's Target/assignment/contribution rows and
 *  runs the pure cascade above, capped at today's elapsed working days. An
 *  explicit principal filter narrows all three inputs before attribution so a
 *  filtered ranking cannot retain unrelated Team Leaders or portfolio targets. */
export async function getMtdTargetByTeamLeader(year: string, monthLabel: string, principals: string[] = []): Promise<MtdTargetRow[]> {
  const monthIndex = CANONICAL_MONTHS.indexOf(monthLabel);
  if (monthIndex < 0) return [];
  const principalWhere = principals.length > 0 ? { principal: { in: principals } } : {};

  const [principalTargets, assignments, contributions] = await Promise.all([
    prisma.target.findMany({ where: { year, month: monthLabel, ...principalWhere }, select: { principal: true, valueTarget: true } }),
    prisma.teamLeaderAssignment.findMany({
      where: { active: true, salesRole: "PRIMARY", ...principalWhere },
      select: { teamLeaderId: true, principal: true, employeeCode: true, contributionPct: true },
    }),
    prisma.repContribution.findMany({ where: principalWhere, select: { principal: true, employeeCode: true, sharePct: true } }),
  ]);

  const workingDaysInMonth = countWorkingDaysInMonth(Number(year), monthIndex);
  const workingDaysElapsed = countElapsedWorkingDays(Number(year), monthIndex);

  return computeMtdTargetByTeamLeader({ principalTargets, assignments, contributions }, workingDaysElapsed, workingDaysInMonth);
}
