// True month-to-date Target per Team Leader, for TL/Supervisor/Manager Ranking.
//
// buildTlRanking's mtdTarget has been wrong through two prior attempts:
//
// 1. Originally a straight sum of every WeeklyTarget row for the month (all
//    weeks, including ones that haven't started) - a full-month figure
//    mislabeled "MTD," and fragmented by legacy Team Leader identities
//    (orphaned pre-restructuring WeeklyTarget history under a stale
//    teamLeaderId nobody currently reports through).
// 2. Then switched to summing DailyTarget (which weekday-expands each
//    WeeklyTarget row) capped at today - fixed the elapsed-days problem, but
//    DailyTarget is generated by exploding WeeklyTarget rows against whichever
//    reps are CURRENTLY active under that row's exact teamLeaderId+principal
//    pair (recomputeDailyTargets, lib/repContribution.ts). A Supervisor whose
//    real reps sit under newer Team Leader identities, while their own legacy
//    teamLeaderId carries the real WeeklyTarget money but zero active reps,
//    still collapsed to a near-zero MTD Target (confirmed live: Lucy Githinji
//    ~5K against a ~90M monthly target).
//
// This version instead cascades the admin-entered Target.valueTarget (the same
// number already shown correctly on Sales Performance vs Target) down through
// RepContribution.sharePct (which sums to 100% among a principal's currently
// active Primary reps) to Team Leader, then prorates by elapsed working days.
// Driven entirely by current rosters/contributions - a Team Leader with zero
// currently-active Primary reps simply never enters the output, so no
// legacy-identity special-casing is needed on the target side at all.
import { prisma } from "@/lib/db";
import { CANONICAL_MONTHS } from "@/lib/timeIntelligence";
import { resolveRepSharePct } from "@/lib/repContribution";

export interface MtdTargetRow {
  teamLeaderId: string;
  targetValue: number;
  /** The same cascade's full-month figure, before the working-days proration -
   *  every Team Leader's monthlyTargetValue sums up to exactly the principal
   *  Target totals it was split from (contribution shares sum to 100%), so
   *  Supervisor/Manager rollups of this tie out to the overall month target. */
  monthlyTargetValue: number;
}

/** Mon-Fri, matching the work-week definition lib/repContribution.ts already
 *  uses to weekday-expand WeeklyTarget into DailyTarget (WEEKDAY_LABELS) -
 *  reused here rather than inventing a second definition. */
function isWorkingDay(date: Date): boolean {
  const day = date.getUTCDay();
  return day >= 1 && day <= 5;
}

/** Every Mon-Fri UTC calendar day in the given month. */
export function countWorkingDaysInMonth(year: number, monthIndex: number): number {
  const daysInMonth = new Date(Date.UTC(year, monthIndex + 1, 0)).getUTCDate();
  let count = 0;
  for (let d = 1; d <= daysInMonth; d++) {
    if (isWorkingDay(new Date(Date.UTC(year, monthIndex, d)))) count++;
  }
  return count;
}

/** Working days from the 1st through `today` inclusive - 0 if `today` is
 *  before the month starts, every working day in the month if `today` is
 *  after it ends (a fully-elapsed past month counts as 100% done). */
export function countElapsedWorkingDays(year: number, monthIndex: number, today: Date = new Date()): number {
  const monthStart = new Date(Date.UTC(year, monthIndex, 1));
  const daysInMonth = new Date(Date.UTC(year, monthIndex + 1, 0)).getUTCDate();
  const monthEnd = new Date(Date.UTC(year, monthIndex, daysInMonth));
  const todayUtc = new Date(Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate()));

  if (todayUtc < monthStart) return 0;
  const through = todayUtc > monthEnd ? monthEnd : todayUtc;

  let count = 0;
  for (let d = new Date(monthStart); d <= through; d = new Date(d.getTime() + 86400000)) {
    if (isWorkingDay(d)) count++;
  }
  return count;
}

export interface MtdTargetInputs {
  /** One row per principal, e.g. from Target.findMany - the admin-entered
   *  monthly figure, already shown correctly on Sales Performance vs Target. */
  principalTargets: { principal: string; valueTarget: number | null }[];
  /** Active, PRIMARY-role TeamLeaderAssignment rows only - actual SAP sales
   *  targets are a Primary concern (see lib/repContribution.ts's header note). */
  assignments: { teamLeaderId: string; principal: string; employeeCode: string; contributionPct: number | null }[];
  /** RepContribution rows - a rep's share of a principal's trailing revenue
   *  among reps currently assigned to it. */
  contributions: { principal: string; employeeCode: string; sharePct: number }[];
}

/** Splits each principal's monthly Target across its currently-active Primary
 *  reps by contribution share, rolls that up to Team Leader, then prorates by
 *  elapsed working days. Mirrors recomputeDailyTargets's own grouping exactly
 *  (group by teamLeaderId+principal from raw assignments, not
 *  RepContribution.teamLeaderId, which only records a rep's first-seen Team
 *  Leader and would silently drop a matrix-assigned rep's second team) -
 *  same reasoning DailyTarget's own composite-key comment already documents. */
export function computeMtdTargetByTeamLeader(inputs: MtdTargetInputs, workingDaysElapsed: number, workingDaysInMonth: number): MtdTargetRow[] {
  const { principalTargets, assignments, contributions } = inputs;

  const targetByPrincipal = new Map(principalTargets.map((t) => [t.principal, t.valueTarget ?? 0]));
  const shareByPrincipalRep = new Map(contributions.map((c) => [`${c.principal}|${c.employeeCode}`, c.sharePct]));

  const repsByTeamLeaderPrincipal = new Map<string, { employeeCode: string; contributionPct: number | null }[]>();
  for (const a of assignments) {
    const key = `${a.teamLeaderId}|${a.principal}`;
    const list = repsByTeamLeaderPrincipal.get(key) ?? [];
    list.push({ employeeCode: a.employeeCode, contributionPct: a.contributionPct });
    repsByTeamLeaderPrincipal.set(key, list);
  }

  const prorateFactor = workingDaysInMonth > 0 ? workingDaysElapsed / workingDaysInMonth : 0;
  const monthlyTargetByTeamLeader = new Map<string, number>();

  for (const [key, reps] of repsByTeamLeaderPrincipal) {
    const separatorIndex = key.indexOf("|");
    const teamLeaderId = key.slice(0, separatorIndex);
    const principal = key.slice(separatorIndex + 1);
    const principalTarget = targetByPrincipal.get(principal) ?? 0;
    if (principalTarget === 0) continue;

    let sum = monthlyTargetByTeamLeader.get(teamLeaderId) ?? 0;
    for (const rep of reps) {
      const sharePct = resolveRepSharePct(rep.contributionPct, shareByPrincipalRep.get(`${principal}|${rep.employeeCode}`), 1 / reps.length);
      sum += principalTarget * sharePct;
    }
    monthlyTargetByTeamLeader.set(teamLeaderId, sum);
  }

  return Array.from(monthlyTargetByTeamLeader.entries()).map(([teamLeaderId, monthlyTarget]) => ({
    teamLeaderId,
    targetValue: monthlyTarget * prorateFactor,
    monthlyTargetValue: monthlyTarget,
  }));
}

/** Async wrapper: fetches this month's Target/assignment/contribution rows and
 *  runs the pure cascade above, capped at today's elapsed working days. No
 *  `principal` narrowing param - none of this function's 3 call sites have ever
 *  passed one (each Team Leader's full cross-principal target is always shown,
 *  regardless of any principal filter applied to the revenue side - see the
 *  matching comment in app/api/dashboard/tl-ranking/route.ts). */
export async function getMtdTargetByTeamLeader(year: string, monthLabel: string): Promise<MtdTargetRow[]> {
  const monthIndex = CANONICAL_MONTHS.indexOf(monthLabel);
  if (monthIndex < 0) return [];

  const [principalTargets, assignments, contributions] = await Promise.all([
    prisma.target.findMany({ where: { year, month: monthLabel }, select: { principal: true, valueTarget: true } }),
    prisma.teamLeaderAssignment.findMany({
      where: { active: true, salesRole: "PRIMARY" },
      select: { teamLeaderId: true, principal: true, employeeCode: true, contributionPct: true },
    }),
    prisma.repContribution.findMany({ select: { principal: true, employeeCode: true, sharePct: true } }),
  ]);

  const workingDaysInMonth = countWorkingDaysInMonth(Number(year), monthIndex);
  const workingDaysElapsed = countElapsedWorkingDays(Number(year), monthIndex);

  return computeMtdTargetByTeamLeader({ principalTargets, assignments, contributions }, workingDaysElapsed, workingDaysInMonth);
}
